version: "3.8"

services:
  api:
    build: .
    container_name: housing-api
    ports:
      - "5000:5000"
    environment:
      DB_USER: housing_user
      DB_PASSWORD: housing_user
      DB_HOST: db  # Correspond au nom du service PostgreSQL
      DB_PORT: 5432
      DB_NAME: housing
      FLASK_DEBUG: 1
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: housing-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: housing_user
      POSTGRES_PASSWORD: housing_user
      POSTGRES_DB: housing
