version: "3.8"  # Version de Docker Compose utilisée

services:
  api:  # Définition du service de l'API Flask
    build: .  # Construire l'image à partir du Dockerfile dans le répertoire actuel
    container_name: housing-api  # Nom attribué au conteneur pour une identification facile
    ports:
      - "5000:5000"  # Mappage du port du conteneur vers l'hôte (accès à l'API via http://localhost:5000)
    environment:  # Définition des variables d'environnement utilisées par l'application Flask
      DB_USER: housing_user  # Nom d'utilisateur pour PostgreSQL
      DB_PASSWORD: housing_user  # Mot de passe pour PostgreSQL
      DB_HOST: db  # Correspond au nom du service PostgreSQL (Docker le résout automatiquement)
      DB_PORT: 5432  # Port PostgreSQL utilisé
      DB_NAME: housing  # Nom de la base de données PostgreSQL
      FLASK_DEBUG: 1  # Mode debug activé pour le développement
    depends_on:  # L'API dépend du service db (PostgreSQL), donc db sera lancé en premier
      - db

  db:  # Définition du service PostgreSQL
    image: postgres:13  # Utilisation de l'image officielle PostgreSQL version 13
    container_name: housing-db  # Nom attribué au conteneur pour PostgreSQL
    ports:
      - "5432:5432"  # Mappage du port PostgreSQL pour y accéder depuis l'hôte
    environment:  # Définition des variables d'environnement pour PostgreSQL
      POSTGRES_USER: housing_user  # Nom d'utilisateur PostgreSQL
      POSTGRES_PASSWORD: housing_user  # Mot de passe PostgreSQL
      POSTGRES_DB: housing  # Nom de la base de données à créer automatiquement
